/* Copyright Ideas4Learning 2017. http.//ideas4learning.com */

var conection = true; // Conecta o no con el LMS.
var mostrarAlertas = false; // Muestra las alertas de fallo de conexión.
var contentPath = "contenido/"; // Directorio de contenido.
var modulos = 1; // No. total de módulos con evaluación.
var mobileCurse = false; // Fuerza la vista para dispositivos móviles.
var navegationBlock = true; // Bloquea o libera la navegación libre.
var haySubtitulos = false;
var intentos = 0;
var intento = 1;
var cuantosEjercicios = 2;

/* Listado de pantalla del curso */
var course = new Object();
course.pages = [
    { title: "eLearning", url: "SANOFI_HSE_01.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_02.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_03.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_04.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_05.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_06.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_07.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_08.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_09_1.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_10.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_09_2.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_12.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_09_3.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_13.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_09_4.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_11.html", navegacion: true, menu: true },   
    { title: "eLearning", url: "SANOFI_HSE_09_5.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_14.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_09_6.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_15.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_16.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_17.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_18.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_19.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_19_0.html", navegacion: true, menu: true },
    //{ title: "eLearning", url: "SANOFI_HSE_19_1.html", navegacion: true, menu: true },
    //{ title: "eLearning", url: "SANOFI_HSE_19_2.html", navegacion: true, menu: true },
    //{ title: "eLearning", url: "SANOFI_HSE_19_3.html", navegacion: true, menu: true },

    // { title: "eLearning", url: "SANOFI_HSE_19_4.html", navegacion: true, menu: true },
     { title: "eLearning", url: "SANOFI_HSE_19_5.html", navegacion: true, menu: true },
    // { title: "eLearning", url: "SANOFI_HSE_19_6.html", navegacion: true, menu: true },
    // { title: "eLearning", url: "SANOFI_HSE_19_8.html", navegacion: true, menu: true },
    //{ title: "eLearning", url: "SANOFI_HSE_19_10.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_20.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_21.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_21_1.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_22.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_23.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_23_1.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_24.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_25.html", navegacion: true, menu: true },   
    { title: "eLearning", url: "SANOFI_HSE_26.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_26_1.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_27.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_28.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_29.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_30.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_31.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_32.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_33.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_34.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_35.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_36.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_37.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_37_1.html", navegacion: true, menu: true },
    { title: "eLearning", url: "SANOFI_HSE_38.html", navegacion: true, menu: true }
    
];


/* audios del curso */
var grupoAudios = new buzz.group([
 /*0*/  new  buzz.sound("contenido/audios/audio0", { formats: ["mp3"], preload: true }),
/*1*/   new buzz.sound("contenido/audios/SIndustrial_HSE_01_01", { formats: ["mp3"], preload: true }),
/*2*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_01", { formats: ["mp3"], preload: true }),
/*3*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_02", { formats: ["mp3"], preload: true }),
/*4*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_03", { formats: ["mp3"], preload: true }),
/*5*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_04", { formats: ["mp3"], preload: true }),
/*6*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_05", { formats: ["mp3"], preload: true }),
/*7*/	new buzz.sound("contenido/audios/SIndustrial_HSE_02_06", { formats: ["mp3"], preload: true }),
/*8*/	new buzz.sound("contenido/audios/SIndustrial_HSE_03_01", { formats: ["mp3"], preload: true }),
/*9*/   new buzz.sound("contenido/audios/SIndustrial_HSE_04_01", { formats: ["mp3"], preload: true }),
/*10*/  new buzz.sound("contenido/audios/SIndustrial_HSE_04_02", { formats: ["mp3"], preload: true }),
/*11*/  new buzz.sound("contenido/audios/SIndustrial_HSE_04_03", { formats: ["mp3"], preload: true }),
/*12*/  new buzz.sound("contenido/audios/SIndustrial_HSE_04_04", { formats: ["mp3"], preload: true }),
/*13*/  new buzz.sound("contenido/audios/SIndustrial_HSE_05_01", { formats: ["mp3"], preload: true }),
/*14*/  new buzz.sound("contenido/audios/SIndustrial_HSE_06_01", { formats: ["mp3"], preload: true }),
/*15*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_01", { formats: ["mp3"], preload: true }),
/*16*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_02", { formats: ["mp3"], preload: true }),
/*17*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_03", { formats: ["mp3"], preload: true }),
/*18*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_04", { formats: ["mp3"], preload: true }),
/*19*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_05", { formats: ["mp3"], preload: true }),
/*20*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_06", { formats: ["mp3"], preload: true }),
/*21*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_07", { formats: ["mp3"], preload: true }),
/*22*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_08", { formats: ["mp3"], preload: true }),
/*23*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_09", { formats: ["mp3"], preload: true }),
/*24*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_10", { formats: ["mp3"], preload: true }),
/*25*/  new buzz.sound("contenido/audios/SIndustrial_HSE_07_11", { formats: ["mp3"], preload: true }),
/*26*/  new  buzz.sound("contenido/audios/SIndustrial_HSE_07_12", { formats: ["mp3"], preload: true }),
/*27*/   new buzz.sound("contenido/audios/SIndustrial_HSE_08_01", { formats: ["mp3"], preload: true }),
/*28*/   new buzz.sound("contenido/audios/SIndustrial_HSE_09_01", { formats: ["mp3"], preload: true }),
/*29*/   new buzz.sound("contenido/audios/SIndustrial_HSE_10_01", { formats: ["mp3"], preload: true }),
/*30*/   new buzz.sound("contenido/audios/SIndustrial_HSE_10_02", { formats: ["mp3"], preload: true }),
/*31*/   new buzz.sound("contenido/audios/SIndustrial_HSE_11_01", { formats: ["mp3"], preload: true }),
/*32*/   new buzz.sound("contenido/audios/SIndustrial_HSE_11_02", { formats: ["mp3"], preload: true }),
/*33*/   new buzz.sound("contenido/audios/SIndustrial_HSE_12_01", { formats: ["mp3"], preload: true }),
/*34*/   new buzz.sound("contenido/audios/SIndustrial_HSE_12_02", { formats: ["mp3"], preload: true }),
/*35*/   new buzz.sound("contenido/audios/SIndustrial_HSE_13_01", { formats: ["mp3"], preload: true }),
/*36*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02", { formats: ["mp3"], preload: true }),
/*37*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_03", { formats: ["mp3"], preload: true }),
/*38*/  new buzz.sound("contenido/audios/SIndustrial_HSE_14_01", { formats: ["mp3"], preload: true }),
/*39*/  new buzz.sound("contenido/audios/SIndustrial_HSE_14_02", { formats: ["mp3"], preload: true }),
/*40*/  new buzz.sound("contenido/audios/SIndustrial_HSE_14_03", { formats: ["mp3"], preload: true }),
/*41*/  new buzz.sound("contenido/audios/SIndustrial_HSE_15_01", { formats: ["mp3"], preload: true }),
/*42*/  new buzz.sound("contenido/audios/SIndustrial_HSE_15_02", { formats: ["mp3"], preload: true }),
/*43*/  new buzz.sound("contenido/audios/SIndustrial_HSE_16_01", { formats: ["mp3"], preload: true }),
/*44*/  new buzz.sound("contenido/audios/SIndustrial_HSE_16_02", { formats: ["mp3"], preload: true }),
/*45*/   new buzz.sound("contenido/audios/SIndustrial_HSE_17_01", { formats: ["mp3"], preload: true }),
/*46*/   new buzz.sound("contenido/audios/SIndustrial_HSE_18_01", { formats: ["mp3"], preload: true }),
/*47*/   new buzz.sound("contenido/audios/SIndustrial_HSE_18_02", { formats: ["mp3"], preload: true }),
/*48*/   new buzz.sound("contenido/audios/SIndustrial_HSE_19_01", { formats: ["mp3"], preload: true }),
/*49*/   new buzz.sound("contenido/audios/SIndustrial_HSE_19_02", { formats: ["mp3"], preload: true }),
/*50*/   new buzz.sound("contenido/audios/SIndustrial_HSE_19_03", { formats: ["mp3"], preload: true }),
/*51*/   new buzz.sound("contenido/audios/SIndustrial_HSE_19_04", { formats: ["mp3"], preload: true }),
/*52*/   new buzz.sound("contenido/audios/SIndustrial_HSE_19_05", { formats: ["mp3"], preload: true }),
/*53*/   new buzz.sound("contenido/audios/SIndustrial_HSE_20_01", { formats: ["mp3"], preload: true }),
/*54*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_02", { formats: ["mp3"], preload: true }),
/*55*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_03", { formats: ["mp3"], preload: true }),
/*56*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_04", { formats: ["mp3"], preload: true }),
/*57*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_05", { formats: ["mp3"], preload: true }),
/*58*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_06", { formats: ["mp3"], preload: true }),
/*59*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_07", { formats: ["mp3"], preload: true }),
/*60*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_08", { formats: ["mp3"], preload: true }),
/*61*/  new buzz.sound("contenido/audios/SIndustrial_HSE_20_09", { formats: ["mp3"], preload: true }),
/*62*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_01", { formats: ["mp3"], preload: true }),
/*63*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_02", { formats: ["mp3"], preload: true }),
/*64*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_03", { formats: ["mp3"], preload: true }),
/*65*/  new buzz.sound("contenido/audios/SIndustrial_HSE_22_01", { formats: ["mp3"], preload: true }),
/*66*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_01", { formats: ["mp3"], preload: true }),
/*67*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_02", { formats: ["mp3"], preload: true }),
/*68*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_03", { formats: ["mp3"], preload: true }),
/*69*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_04", { formats: ["mp3"], preload: true }),
/*70*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_05", { formats: ["mp3"], preload: true }),
/*71*/  new buzz.sound("contenido/audios/SIndustrial_HSE_23_06", { formats: ["mp3"], preload: true })
// /*72*/  new buzz.sound("contenido/audios/SIndustrial_HSE_24_01", { formats: ["mp3"], preload: true }),
// /*73*/  new buzz.sound("contenido/audios/SIndustrial_HSE_24_02", { formats: ["mp3"], preload: true }),
// /*74*/  new buzz.sound("contenido/audios/SIndustrial_HSE_24_03", { formats: ["mp3"], preload: true }),
// /*75*/  new buzz.sound("contenido/audios/SIndustrial_HSE_24_04", { formats: ["mp3"], preload: true }),
// /*76*/  new buzz.sound("contenido/audios/SIndustrial_HSE_25_01", { formats: ["mp3"], preload: true }),
// /*77*/  new buzz.sound("contenido/audios/SIndustrial_HSE_26_01", { formats: ["mp3"], preload: true }),
// /*78*/  new buzz.sound("contenido/audios/SIndustrial_HSE_26_02", { formats: ["mp3"], preload: true }),
// /*79*/  new buzz.sound("contenido/audios/SIndustrial_HSE_26_03", { formats: ["mp3"], preload: true }),
// /*80*/  new buzz.sound("contenido/audios/SIndustrial_HSE_27_01", { formats: ["mp3"], preload: true }),
// /*81*/  new buzz.sound("contenido/audios/SIndustrial_HSE_28_01", { formats: ["mp3"], preload: true }),
// /*82*/  new buzz.sound("contenido/audios/SIndustrial_HSE_29_01", { formats: ["mp3"], preload: true }),
// /*83*/  new buzz.sound("contenido/audios/SIndustrial_HSE_29_02", { formats: ["mp3"], preload: true }),
// /*84*/  new buzz.sound("contenido/audios/SIndustrial_HSE_30_01", { formats: ["mp3"], preload: true }),
// /*85*/  new buzz.sound("contenido/audios/SIndustrial_HSE_31_01", { formats: ["mp3"], preload: true }),
// /*86*/  new buzz.sound("contenido/audios/SIndustrial_HSE_31_02", { formats: ["mp3"], preload: true }),
// /*87*/  new buzz.sound("contenido/audios/SIndustrial_HSE_31_03", { formats: ["mp3"], preload: true }),
// /*88*/  new buzz.sound("contenido/audios/SIndustrial_HSE_31_04", { formats: ["mp3"], preload: true }),
// /*89*/  new buzz.sound("contenido/audios/SIndustrial_HSE_32_01", { formats: ["mp3"], preload: true }),
// /*90*/  new buzz.sound("contenido/audios/SIndustrial_HSE_32_02", { formats: ["mp3"], preload: true }),
// /*91*/  new buzz.sound("contenido/audios/SIndustrial_HSE_32_03", { formats: ["mp3"], preload: true }),
// /*92*/  new buzz.sound("contenido/audios/SIndustrial_HSE_32_04", { formats: ["mp3"], preload: true }),
// /*93*/  new buzz.sound("contenido/audios/SIndustrial_HSE_32_05", { formats: ["mp3"], preload: true }),
// /*94*/  new buzz.sound("contenido/audios/SIndustrial_HSE_33_01", { formats: ["mp3"], preload: true }),
// /*95*/  new buzz.sound("contenido/audios/SIndustrial_HSE_33_02", { formats: ["mp3"], preload: true }),
// /*96*/  new buzz.sound("contenido/audios/SIndustrial_HSE_33_03", { formats: ["mp3"], preload: true }),
// /*97*/  new buzz.sound("contenido/audios/SIndustrial_HSE_33_04", { formats: ["mp3"], preload: true }),
// /*98*/  new buzz.sound("contenido/audios/SIndustrial_HSE_34_01", { formats: ["mp3"], preload: true }),
// /*99*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_01", { formats: ["mp3"], preload: true }),
// /*100*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_02", { formats: ["mp3"], preload: true }),
// /*101*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_03", { formats: ["mp3"], preload: true }),
// /*102*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_04", { formats: ["mp3"], preload: true }),
// /*103*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_05", { formats: ["mp3"], preload: true }),
// /*104*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_06", { formats: ["mp3"], preload: true }),
// /*105*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_07", { formats: ["mp3"], preload: true }),
// /*106*/  new buzz.sound("contenido/audios/SIndustrial_HSE_36_01", { formats: ["mp3"], preload: true }),
// /*107*/  new buzz.sound("contenido/audios/SIndustrial_HSE_36_02", { formats: ["mp3"], preload: true }),
// /*108*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_01", { formats: ["mp3"], preload: true }),
// /*109*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_02", { formats: ["mp3"], preload: true }),
// /*110*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_03", { formats: ["mp3"], preload: true }),
// /*111*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_04", { formats: ["mp3"], preload: true }),
// /*112*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_05", { formats: ["mp3"], preload: true }),
// /*113*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_06", { formats: ["mp3"], preload: true }),
// /*114*/  new buzz.sound("contenido/audios/SIndustrial_HSE_37_07", { formats: ["mp3"], preload: true }),
// /*115*/  new buzz.sound("contenido/audios/SIndustrial_HSE_38_01", { formats: ["mp3"], preload: true }),
// /*116*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_04", { formats: ["mp3"], preload: true }),
// /*117*/  new buzz.sound("contenido/audios/s_bien", { formats: ["mp3"], preload: true }),
// /*118*/  new buzz.sound("contenido/audios/s_mal", { formats: ["mp3"], preload: true }),
// /*119*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_02b", { formats: ["mp3"], preload: true }),
// /*120*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_04b", { formats: ["mp3"], preload: true }),
// /*121*/  new buzz.sound("contenido/audios/SIndustrial_HSE_35_06b", { formats: ["mp3"], preload: true }),
// /*122*/  new buzz.sound("contenido/audios/SIndustrial_HSE_19_02_extra", { formats: ["mp3"], preload: true }),
// /*123*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_01", { formats: ["mp3"], preload: true }),
// /*124*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_02", { formats: ["mp3"], preload: true }),
// /*125*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_03", { formats: ["mp3"], preload: true }),
// /*126*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_04", { formats: ["mp3"], preload: true }),
// /*127*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_05", { formats: ["mp3"], preload: true }),
// /*128*/  new buzz.sound("contenido/audios/SIndustrial_HSE_11_02_06", { formats: ["mp3"], preload: true }),

// /*129*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02_01", { formats: ["mp3"], preload: true }),
// /*130*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02_02", { formats: ["mp3"], preload: true }),
// /*131*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02_03", { formats: ["mp3"], preload: true }),
// /*132*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02_04", { formats: ["mp3"], preload: true }),
// /*133*/  new buzz.sound("contenido/audios/SIndustrial_HSE_13_02_05", { formats: ["mp3"], preload: true }),
// /*134*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_04_1", { formats: ["mp3"], preload: true }),
// /*135*/  new buzz.sound("contenido/audios/SIndustrial_HSE_21_04_2", { formats: ["mp3"], preload: true }),


]);
