/* Copyright Ideas4Learning 2017. http.//ideas4learning.com */

var conection = true; // Conecta o no con el LMS.
var mostrarAlertas = false; // Muestra las alertas de fallo de conexión.
var contentPath = "contenido/"; // Directorio de contenido.
var modulos = 1; // No. total de módulos con evaluación.
var mobileCurse = false; // Fuerza la vista para dispositivos móviles.
var navegationBlock = true; // Bloquea o libera la navegación libre.
var haySubtitulos = false;
var intentos = 0;
var intento = 1;
var cuantosEjercicios = 2;

/* Listado de pantalla del curso */
var course = new Object();
course.pages = [
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_01.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_02.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_03.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_04.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_05.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_06.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_07.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_08.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_09.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_10.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_11.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_12.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_13.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_14.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_15.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_16.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_17.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_18.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_19.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_20.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_21.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_22.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_23.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_24.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_25.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_26.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_27.html", navegacion: true, menu: true },
    { title: "eLearning", url: "San-Ofi-Sist-manofactura_28.html", navegacion: true, menu: true }
    
    
    
   
    
];


/* audios del curso */
var grupoAudios = new buzz.group([
/*0*/  new  buzz.sound("contenido/audios/audio0", { formats: ["mp3"], preload: true }),
/*1*/   new buzz.sound("contenido/audios/Sanofi_ONBSMS_01_1", { formats: ["mp3"], preload: true }),
/*2*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_02_1", { formats: ["mp3"], preload: true }),
/*3*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_02_2", { formats: ["mp3"], preload: true }),
/*4*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_02_3", { formats: ["mp3"], preload: true }),
/*5*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_02_4", { formats: ["mp3"], preload: true }),
/*6*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_03_1", { formats: ["mp3"], preload: true }),
/*7*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_04_1", { formats: ["mp3"], preload: true }),
/*8*/	new buzz.sound("contenido/audios/Sanofi_ONBSMS_04_2", { formats: ["mp3"], preload: true }),
/*9*/   new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_1", { formats: ["mp3"], preload: true }),
/*10*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_2", { formats: ["mp3"], preload: true }),
/*11*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_3", { formats: ["mp3"], preload: true }),
/*12*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_4", { formats: ["mp3"], preload: true }),
/*13*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_5", { formats: ["mp3"], preload: true }),
/*14*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_6", { formats: ["mp3"], preload: true }),
/*15*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_7", { formats: ["mp3"], preload: true }),
/*16*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_8", { formats: ["mp3"], preload: true }),
/*17*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_05_9", { formats: ["mp3"], preload: true }),
/*18*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_1", { formats: ["mp3"], preload: true }),
/*19*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_2", { formats: ["mp3"], preload: true }),
/*20*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_3", { formats: ["mp3"], preload: true }),

/*21*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_4", { formats: ["mp3"], preload: true }),
/*22*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_5", { formats: ["mp3"], preload: true }),
/*23*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_6", { formats: ["mp3"], preload: true }),
/*24*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_7", { formats: ["mp3"], preload: true }),
/*25*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_8", { formats: ["mp3"], preload: true }),
/*26*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_9", { formats: ["mp3"], preload: true }),
/*27*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_10", { formats: ["mp3"], preload: true }),
/*28*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_11", { formats: ["mp3"], preload: true }),
/*29*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_06_12", { formats: ["mp3"], preload: true }),
/*30*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_07_1", { formats: ["mp3"], preload: true }),
/*31*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_07_2", { formats: ["mp3"], preload: true }),
/*32*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_07_3", { formats: ["mp3"], preload: true }),
/*33*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_1", { formats: ["mp3"], preload: true }),
/*34*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_2", { formats: ["mp3"], preload: true }),
/*35*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_3", { formats: ["mp3"], preload: true }),
/*36*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_4", { formats: ["mp3"], preload: true }),
/*37*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_5", { formats: ["mp3"], preload: true }),
/*38*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_08_6", { formats: ["mp3"], preload: true }),
/*39*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_1", { formats: ["mp3"], preload: true }),
/*40*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_2", { formats: ["mp3"], preload: true }),

/*41*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_3", { formats: ["mp3"], preload: true }),
/*42*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_4", { formats: ["mp3"], preload: true }),
/*43*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_5", { formats: ["mp3"], preload: true }),
/*44*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_6", { formats: ["mp3"], preload: true }),
/*45*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_09_7", { formats: ["mp3"], preload: true }),
/*46*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_1", { formats: ["mp3"], preload: true }),
/*47*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_2", { formats: ["mp3"], preload: true }),
/*48*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_3", { formats: ["mp3"], preload: true }),
/*49*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_4", { formats: ["mp3"], preload: true }),
/*50*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_5", { formats: ["mp3"], preload: true }),
/*51*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_6", { formats: ["mp3"], preload: true }),
/*52*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_10_7", { formats: ["mp3"], preload: true }),
/*53*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_1", { formats: ["mp3"], preload: true }),
/*54*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_2", { formats: ["mp3"], preload: true }),
/*55*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_3", { formats: ["mp3"], preload: true }),
/*56*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_4", { formats: ["mp3"], preload: true }),
/*57*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_5", { formats: ["mp3"], preload: true }),
/*58*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_6", { formats: ["mp3"], preload: true }),
/*59*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_7", { formats: ["mp3"], preload: true }),
/*60*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_8", { formats: ["mp3"], preload: true }),
/*61*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_11_9", { formats: ["mp3"], preload: true }),
/*62*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_12_1", { formats: ["mp3"], preload: true }),
/*63*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_12_2", { formats: ["mp3"], preload: true }),
/*64*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_12_3", { formats: ["mp3"], preload: true }),
/*65*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_12_4", { formats: ["mp3"], preload: true }),
/*66*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_13_1", { formats: ["mp3"], preload: true }),
/*67*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_13_2", { formats: ["mp3"], preload: true }),
/*68*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_13_3", { formats: ["mp3"], preload: true }),
/*69*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_13_4", { formats: ["mp3"], preload: true }),
/*70*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_13_5", { formats: ["mp3"], preload: true }),
/*71*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_14_1", { formats: ["mp3"], preload: true }),
/*72*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_15_1", { formats: ["mp3"], preload: true }),
/*73*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_15_2", { formats: ["mp3"], preload: true }),
/*74*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_15_3", { formats: ["mp3"], preload: true }),
/*75*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_15_4", { formats: ["mp3"], preload: true }),
/*76*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_15_5", { formats: ["mp3"], preload: true }),
/*77*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_16_1", { formats: ["mp3"], preload: true }),
/*78*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_17_1", { formats: ["mp3"], preload: true }),
/*79*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_17_2", { formats: ["mp3"], preload: true }),
/*80*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_17_3", { formats: ["mp3"], preload: true }),
/*81*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_17_4", { formats: ["mp3"], preload: true }),
/*82*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_17_5", { formats: ["mp3"], preload: true }),
/*83*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_18_1", { formats: ["mp3"], preload: true }),
/*84*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_18_2", { formats: ["mp3"], preload: true }),
/*85*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_18_3", { formats: ["mp3"], preload: true }),
/*86*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_18_4", { formats: ["mp3"], preload: true }),

/*87*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_19_1", { formats: ["mp3"], preload: true }),
/*88*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_19_2", { formats: ["mp3"], preload: true }),
/*89*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_19_3", { formats: ["mp3"], preload: true }),
/*90*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_1", { formats: ["mp3"], preload: true }),
/*91*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_2", { formats: ["mp3"], preload: true }),
/*92*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_3", { formats: ["mp3"], preload: true }),
/*93*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_4", { formats: ["mp3"], preload: true }),
/*94*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_5", { formats: ["mp3"], preload: true }),
/*95*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_20_6", { formats: ["mp3"], preload: true }),
/*96*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_1", { formats: ["mp3"], preload: true }),
/*97*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_2", { formats: ["mp3"], preload: true }),
/*98*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_3", { formats: ["mp3"], preload: true }),
/*99*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_4", { formats: ["mp3"], preload: true }),
/*100*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_5", { formats: ["mp3"], preload: true }),
/*101*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_21_6", { formats: ["mp3"], preload: true }),
/*102*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_1", { formats: ["mp3"], preload: true }),
/*103*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_2", { formats: ["mp3"], preload: true }),
/*104*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_3", { formats: ["mp3"], preload: true }),
/*105*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_4", { formats: ["mp3"], preload: true }),
/*106*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_5", { formats: ["mp3"], preload: true }),
/*107*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_6", { formats: ["mp3"], preload: true }),
/*108*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_7", { formats: ["mp3"], preload: true }),
/*109*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_22_8", { formats: ["mp3"], preload: true }),
/*110*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_1", { formats: ["mp3"], preload: true }),
/*111*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_2", { formats: ["mp3"], preload: true }),
/*112*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_3", { formats: ["mp3"], preload: true }),
/*113*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_4", { formats: ["mp3"], preload: true }),
/*114*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_5", { formats: ["mp3"], preload: true }),
/*115*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_6", { formats: ["mp3"], preload: true }),
/*116*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_23_7", { formats: ["mp3"], preload: true }),
/*117*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_24_1", { formats: ["mp3"], preload: true }),
/*118*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_24_2", { formats: ["mp3"], preload: true }),
/*119*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_24_3", { formats: ["mp3"], preload: true }),
/*120*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_24_4", { formats: ["mp3"], preload: true }),
/*121*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_24_5", { formats: ["mp3"], preload: true }),
/*122*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_1", { formats: ["mp3"], preload: true }),
/*123*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_2", { formats: ["mp3"], preload: true }),
/*124*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_3", { formats: ["mp3"], preload: true }),
/*125*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_4", { formats: ["mp3"], preload: true }),
/*126*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_5", { formats: ["mp3"], preload: true }),
/*127*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_6", { formats: ["mp3"], preload: true }),
/*128*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_7", { formats: ["mp3"], preload: true }),
/*129*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_8", { formats: ["mp3"], preload: true }),
/*130*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_9", { formats: ["mp3"], preload: true }),
/*131*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_10", { formats: ["mp3"], preload: true }),
/*132*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_11", { formats: ["mp3"], preload: true }),
/*133*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_12", { formats: ["mp3"], preload: true }),
/*134*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_25_13", { formats: ["mp3"], preload: true }),
/*135*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_26_1", { formats: ["mp3"], preload: true }),
/*136*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_27_1", { formats: ["mp3"], preload: true }),
/*137*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_27_2", { formats: ["mp3"], preload: true }),
/*138*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_28_1", { formats: ["mp3"], preload: true }),
/*139*/  new buzz.sound("contenido/audios/s_bien", { formats: ["mp3"], preload: true }),
/*140*/  new buzz.sound("contenido/audios/s_mal", { formats: ["mp3"], preload: true }),
/*141*/  new buzz.sound("contenido/audios/Sanofi_ONBSMS_19_4", { formats: ["mp3"], preload: true })








]);
